---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: celaeno-fragments-deployment
spec:
  template:
    spec:
      imagePullSecrets:
        - name: gcr-secret
      containers:
        - name: celaeno-fragments-container
          imagePullPolicy: Always
