apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
patchesStrategicMerge:
- deployment.yaml
secretGenerator:
- name: cse-key
  envs:
  - .env
  type: Opaque
images:
- name: app
