apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
patchesStrategicMerge:
- deployment.yaml
secretGenerator:
- files:
  - .env
  name: cse-key
  type: Opaque
images:
- name: app
