version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11
    steps:
      - checkout
      - restore_cache:
          key: sbt-cache
      - run: make jar
      - save_cache:
          key: sbt-cache
          paths:
            - "~/.ivy2/cache"
            - "~/.sbt"
            - "~/.m2"
            - project/target
      - persist_to_workspace:
          root: .
          paths:
            - ops
  gke_deploy:
    # https://cloud.google.com/container-registry/docs/pushing-and-pulling?hl=ja
    environment:
      # CircleCIにて
      # GCP_APP_NAME
      # GCP_PROJECT_ID
      # GCP_CLUSTER_NAME
      # GCP_ZONE
      # GCP_REGION
      # GCP_SERVICE_KEY_ENCODED
      # CSE_API
      # CSE_CX
    docker:
      - image: google/cloud-sdk:latest
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - attach_workspace:
          at: .
      - run:
          name: gcloud setup
          command: |
            gcloud config configurations create ${GCP_PROJECT_ID} 2> /dev/null
            gcloud config configurations activate ${GCP_PROJECT_ID}
            gcloud config set project ${GCP_PROJECT_ID}
            gcloud config set compute/zone ${GCP_ZONE}
            gcloud config set compute/region ${GCP_REGION}
            echo ${GCP_SERVICE_KEY_ENCODED} | base64 -di | gcloud auth activate-service-account --key-file=-
            gcloud config configurations list
            gcloud auth configure-docker --quiet
      - run:
          name: kubectl setup
          command: |
            gcloud container clusters get-credentials ${GCP_CLUSTER_NAME}
      - run:
          name: kustomize setup
          command: |
            curl -s https://api.github.com/repos/kubernetes-sigs/kustomize/releases/latest |\
              grep browser_download |\
              grep linux |\
              cut -d '"' -f 4 |\
              xargs curl -O -L
            mv kustomize_*_linux_amd64 /usr/local/bin/kustomize
            chmod u+x /usr/local/bin/kustomize
      - run:
          name: sudachi setup
          command: |
            apt-get install -y unzip
            curl -O https://object-storage.tyo2.conoha.io/v1/nc_2520839e1f9641b08211a5c85243124a/sudachi/sudachi-dictionary-20190718-full.zip
            unzip sudachi-dictionary-20190718-full.zip
            mv sudachi-dictionary-20190718/system_full.dic ops/app/
      - run:
          name: docker build
          command: docker build -t asia.gcr.io/${GCP_PROJECT_ID}/${GCP_APP_NAME}:${CIRCLE_SHA1} ops/app
      - run:
          name: gcr push
          command: docker push asia.gcr.io/${GCP_PROJECT_ID}/${GCP_APP_NAME}:${CIRCLE_SHA1}
      - run:
          name: gke releasse
          command: |
            ./ops/k8s/overlays/production/build.sh "${CSE_API}" "${CSE_CX}" "asia.gcr.io/${GCP_PROJECT_ID}/${GCP_APP_NAME}:${CIRCLE_SHA1}"
            kubectl apply -f ./ops/k8s/manifest/prd-k8s.yaml
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only: /.*/
      - gke_deploy:
          requires:
            - build
          filters:
            branches:
              only: master
