apiVersion: apps/v1
kind: Deployment
metadata:
  name: celaeno-fragments-deployment
  labels:
    app: celaeno-fragments-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celaeno-fragments-pod
  template:
    metadata:
      labels:
        app: celaeno-fragments-pod
    spec:
      imagePullSecrets:
        - name: gcr-secret
      containers:
        - name: celaeno-fragments-container
          imagePullPolicy: Always
          image: asia.gcr.io/celaeno-fragments/celaeno-fragments-app:latest
