---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: celaeno-fragments-deployment
spec:
  replicas: 1
  template:
    spec:
      volumes:
        - name: application-gcp-secret
          secret:
            secretName: application-gcp-secret
      containers:
        - name: celaeno-fragments-container
          image: app:latest
          env:
            - name: CSE_API
              valueFrom:
                secretKeyRef:
                  name: cse-key
                  key: CSE_API
            - name: CSE_CX
              valueFrom:
                secretKeyRef:
                  name: cse-key
                  key: CSE_CX
