---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: celaeno-fragments-deployment
  labels:
    app: label
spec:
  replicas: 1
  selector:
    matchLabels:
      app: label
  template:
    metadata:
      labels:
        app: label
    spec:
      imagePullSecrets:
        - name: gcr-secret
      containers:
        - name: celaeno-fragments-container
          imagePullPolicy: Always
          image: app:latest
