apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
secretGenerator:
- name: cse-key
  envs:
  - .env
  type: Opaque
images:
- name: app
  newName: celaeno-fragments-app
